{{- if include "github.createSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gar.fullname" . }}-gh-auth
  labels:
    {{- include "gar.labels" . | nindent 4 }}
type: Opaque
data:
  pat: {{ .Values.runner.ghAuth.pat | b64enc | quote }}
{{- end -}}
