# replicaCount -- Number of replicas of the runner pod
replicaCount: 1

# nameOverride -- String to partially override gar.fullname template with a string (will prepend the release name)
nameOverride: ""

# fullnameOverride -- String to fully override gar.fullname template with a string
fullnameOverride: ""

runner:
  image:
    # runner.image.repository -- Github actions runner image name
    repository: aweris/gar
    # runner.image.tag -- Github actions runner image tag
    tag: 2.262.1
    # runner.image.pullPolicy -- Image pull policy
    pullPolicy: Always

  # runner.url -- Repository or Organization url for runner registration
  url:

  # runner.name -- Name of the runner. If not set, new name generated
  name:

  # runner.workdir -- Working directory for the runner
  workdir: /gar/work

  # runner.labels -- Custom labels for the runner
  labels: []

  # runner.githubAuthSecret -- Secret contains [Github authentication](#create-github-authentication-secret) for runner registration
  githubAuthSecret: ""

  # runner.additionalArgs -- [Additional Arguments](#additional-arguments)
  additionalArgs: []

  # runner.resources -- [Resources](#resources)
  resources: {}

  # runner.securityContext -- [Security Context](#security-context)
  securityContext: {}

dind:
  image:
    # dind.image.repository -- DinD image name
    repository: docker
    # dind.image.tag -- DinD image tag
    tag: 19.03-dind
    # dind.image.pullPolicy -- Image pull policy
    pullPolicy: Always

  # dind.resources -- [Resources](#resources)
  resources: {}

  # dind.securityContext -- [Security Context](#security-context)
  # @default -- { privileged: true }
  securityContext:
    privileged: true

serviceAccount:
  # serviceAccount.create -- Specifies whether a service account should be created
  create: true
  # serviceAccount.annotations -- Annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

# podSecurityContext -- [Pod Security Context](#pod-security-context)
podSecurityContext: {}

# extraEnvs -- [Extra Environment Variables](#extra-environment-variables)
extraEnvs: []

# extraVolumeMounts -- [Extra Volume Mounts](#extra-volume-mounts)
extraVolumeMounts: []

# extraVolumes -- [Extra Volumes](#extra-volumes)
extraVolumes: []

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}
# key: value

# tolerations -- Toleration labels for pod assignment
tolerations: []

# affinity -- Affinity settings for pod assignment
affinity: {}
