# replicaCount -- Number of replicas of the runner pod
replicaCount: 1

# nameOverride -- String to partially override gar.fullname template with a string (will prepend the release name)
nameOverride: ""

# fullnameOverride -- String to fully override gar.fullname template with a string
fullnameOverride: ""

runner:
  image:
    # runner.image.repository -- Github actions runner image name
    repository: aweris/gar
    # runner.image.tag -- Github actions runner image tag
    tag: 2.262.1
    # runner.image.pullPolicy -- Image pull policy
    pullPolicy: Always

  # runner.url -- Repository or Organization url for runner registration
  url:

  # runner.name -- Name of the runner. If not set, new name generated
  name:

  # runner.workdir -- Working directory for the runner
  workdir: /gar/work

  # runner.labels -- Custom labels for the runner
  labels: []

  ghAuth:
    # runner.ghAuth.existingSecret -- Secret contains [Github authentication](#create-github-authentication-secret) for runner registration
    existingSecret: ""
    # runner.ghAuth.pat -- Personal access token for Github Authentication. Value will overridden by `runner.ghAuth.existingSecret`
    pat: ""
    # runner.ghAuth.appId -- Github Application ID. Value will overridden by `runner.ghAuth.existingSecret`
    appId:
    # runner.ghAuth.installationId -- Github application installation ID. Value will overridden by `runner.ghAuth.existingSecret`
    installationId:
    # runner.ghAuth.privateKey -- Private key for authenticate as Github application. Value will overridden by `runner.ghAuth.existingSecret`
    privateKey: ""

  # runner.additionalArgs -- [runner.additionalArgs](#runneradditionalargs)
  additionalArgs: []

  # runner.resources -- [resources](#resources)
  resources: {}

  # runner.securityContext -- [securityContext](#securitycontext)
  securityContext: {}

dind:
  image:
    # dind.image.repository -- DinD image name
    repository: docker
    # dind.image.tag -- DinD image tag
    tag: 19.03-dind
    # dind.image.pullPolicy -- Image pull policy
    pullPolicy: Always

  # dind.resources -- [resources](#resources)
  resources: {}

  # dind.securityContext -- [securityContext](#securitycontext)
  # @default -- { privileged: true }
  securityContext:
    privileged: true

serviceAccount:
  # serviceAccount.create -- Specifies whether a service account should be created
  create: true
  # serviceAccount.annotations -- Annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

# podSecurityContext -- [podSecurityContext](#podsecuritycontext)
podSecurityContext: {}

# extraEnvs -- [extraEnvs](#extraenvs)
extraEnvs: []

# extraVolumeMounts -- [extraVolumeMounts](#extravolumemounts)
extraVolumeMounts: []

# extraVolumes -- [extraVolumes](#extravolumes)
extraVolumes: []

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}
# key: value

# tolerations -- Toleration labels for pod assignment
tolerations: []

# affinity -- Affinity settings for pod assignment
affinity: {}
